- hosts: proxy
  remote_user: ansibleman
  become: yes
  tasks:
    - name: copy nginx conf
      template:
        src: ~/ansible/template/location_kanban.tmpl
        dest: /etc/nginx/sites-available/location_kanban
        mode: 0644
        backup: yes
    - name: reload nginx
      shell: nginx -s reload

  vars:
    kanban_server: "{{ lookup('env', 'TARGET') }}"

